### ISSUE TITLE
About close when using dup2()

### ISSUE THREAD

**Issue by oooooorriiiii** [oooooorriiiii/webserv#39]
https://github.com/rnittaBadCommit/webserv/issues/39

**Comment by AuroraSloan** [comment]
I think there is no problem here. maybe we don't need to worry about checking close result in general
and if dup2 fails, an error is thrown here https://github.com/oooooorriiiii/webserv/blob/f4bbdeae451fdb0cb7bbc95e8b20b890cb3869ef/srcs/cgi/Cgi.cpp#L233

and caught here
https://github.com/oooooorriiiii/webserv/blob/f4bbdeae451fdb0cb7bbc95e8b20b890cb3869ef/srcs/httpMethod/HTTPMethod.cpp#L286

and the appropriate error will be sent to the client and the connection closed
