### ISSUE TITLE
Read without poll 

### ISSUE THREAD

**Issue by AuroraSloan** [oooooorriiiii/webserv#57]
https://github.com/oooooorriiiii/webserv/blob/005e9b1938f4f1a9e7004e7bf4bf4661cafc0849/srcs/httpMethod/HTTPMethod.cpp#L282

I'm worried this is not allowed. we are not supposed to read or write to an fd without going through poll first.
Technically poll is run at the beginning or each loop, but cgi fd from fork is not checked by poll
@oooooorriiiii

**Comment by oooooorriiiii** [comment]
I think I am okay with this, but do you think not?

**Comment by AuroraSloan** [comment]
https://discordapp.com/channels/1025574726548074527/1056939635571441724/1056942556816081007
i think #8 bullet means this is not allowed (we use poll instead of select). 
Maybe the reviewer who understands the project well and used Poll will be able to see easily
I can work on a solution, it looks simple to implement. What do you think?

**Comment by AuroraSloan** [comment]
Actually I might be able to solve cgi timeout as well with this. 
by adding the cgi fds to socket's fd_vec, we can ensure using poll for reading and writing, and at the same time, we will be checking the fds for timeout

**Comment by oooooorriiiii** [comment]
Sorry. I don't know anything about poll. If you know the solution, it would help me if you could solve it.

**Comment by AuroraSloan** [comment]
No problem, I'm working on it now
