### ISSUE TITLE
GET sends incorrect content-length

### ISSUE THREAD

**Issue by AuroraSloan** [oooooorriiiii/webserv#62]
Here is output of PUT after uploading a file and then the output of GET for the file that was uploaded
```
➜  webserv git:(upload) ✗ curl http://localhost:8080/foo/index2.html -X PUT
<!DOCTYPE html>
<html>
<h1>Welcome to inception foo index 2 location!</h1>
</html>
➜  webserv git:(upload) ✗ curl http://localhost:8080/foo/index2.html -X GET
<!DOCTYPE html>
<html>
<h1>Welcome to inception foo index 2 location!</h1>
</htm%

**Comment by oooooorriiiii** [comment]
I will confirm. Should I fix it?
Have you come up with a better way to fix it?

**Comment by AuroraSloan** [comment]
if you are okay with having '\n' in the file instead of CRLF, then it is fixed
I think that it is okay
https://github.com/oooooorriiiii/webserv/commit/a20ab6d8774315480332f91710c37931922586c8

**Comment by oooooorriiiii** [comment]
I would like to ask you to fix it.🙏

**Comment by AuroraSloan** [comment]
Oh yes, then it was fixed in the last PR. I will close the issue
