### ISSUE TITLE
non-cgi POST doesn't work

### ISSUE THREAD

**Issue by AuroraSloan** [oooooorriiiii/webserv#64]
do_cgi/cgi constructor assumes that cgi_extentions are used.
However a regular POST request might not have cgi_extention information set

**Comment by AuroraSloan** [comment]
I need it in order to try resolve issue#57, so I'll try to resolve this as well

**Comment by oooooorriiiii** [comment]
I apologize for various flaws in my implementation. Thank you for your cooperation.

**Comment by AuroraSloan** [comment]
I think it's not a flaw, I just misunderstood the purpose of POST.  I'm sorry for the confusion
